// Interests for signup - matches web app TOP_CHOICES
export const SIGNUP_INTERESTS = [
  'Restaurants & Food Scene',
  'Brunch Spots',
  'Street Food',
  'Coffee Shops & Cafes',
  'Late Night Eats',
  'Vegan/Vegetarian',
  'Happy Hour',
  'Craft Beer & Breweries',
  'Wine Bars & Vineyards',
  'Nightlife & Dancing',
  'Live Music',
  'Karaoke',
  'Comedy Shows',
  'Local Hidden Gems',
  'Historical Sites & Tours',
  'Museums',
  'Cultural Experiences',
  'Photography & Scenic Spots',
  'Local Markets & Bazaars',
  'Beach Activities',
  'Water Sports',
  'Hiking',
  'Fitness Classes',
  'Working Out',
  'Golf',
  'Pickleball',
  'Meeting New People',
  'Open to Dating',
  'LGBTQIA+',
  'Family-Oriented',
];
